### PR TITLE
fix(frontend): persistent authentication

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

Persists authentication also when server side rendering utilizing cookies instead of local storage for storage persistency

This is deployed at https://stage1.dreammall.earth/ and can be investigated there.

### Issues

- None

### Todo

- [X] None

### CODE REVIEW

**Comment by ulfgebhardt** [comment]
> I have a problem while testing this: Runing in prod
> 
> * call localhost:3001
> * sign up
> * goes on localhost:3000 and redirect to localhost:3001
> 
> If I call localhost:3000 I get on the page (when I am registered)

This is expected behaviour - oauth does not define a enrollment process - hence we call it manually. This results in the need to login via oauth from the thirdparty.
I guess we could redirect to localhost:300/signin to trigger this process and stay on localhost:3000

**Review by Mogge — CHANGES_REQUESTED** [review]
I cannot sign in anymore. After calling localhost;3000/signin I am always redirected to localhost:3000. Dev and prod the same behavior

**Comment by ulfgebhardt** [comment]
> I cannot sign in anymore. After calling localhost;3000/signin I am always redirected to localhost:3000. Dev and prod the same behavior

You need to accept cookies for this to work

**Review by Mogge — CHANGES_REQUESTED** [review]
On localhost in production
 * I got to localhost:3000/signin
 * I am redirected to authentik
 * I sign in
 * I am redirected to localhost:3000/auth
 * I am redirected to localhost:3001
 
But after this I can visit localhost:3000

**Comment by ulfgebhardt** [comment]
> On localhost in production
> 
> * I got to localhost:3000/signin
> * I am redirected to authentik
> * I sign in
> * I am redirected to localhost:3000/auth
> * I am redirected to localhost:3001
> 
> But after this I can visit localhost:3000

I cannot verify this behaviour - when I run the frontend in dev or production:

```
npm run dev
```
or
```
npm run build
npm run server:prod
```

I get the following:
1. I go to localhost:3000/signin
2. I am redirected to authentik
3. I sign in / am signed in already
4. I am redirected to localhost:3000/auth
5. I am redirected to localhost:3000 and am signed in - i can sign out now

Caching? Other browser related problems? Is my authentik differently configured?

**Review by Mogge — APPROVED** [review]
Wroks, no idea why it did not work before

**Pull request merged**
